global['isBrowser'] = true
require('../src/index-browser')
require('./asset.ts')
require('./blockchain.ts')
require('./broadcast.ts')
require('./client.ts')
require('./crypto.ts')
require('./database.ts')
require('./rc.ts')
require('./misc.ts')
require('./operations.ts')
require('./serializers.ts')
